spin_manifest_version = 2

[application]
name = "wasserspiegel"
version = "0.1.0"
authors = ["Timo Sulg <timgluz@gmail.com>"]
description = "TRML plugin for Wasserspiegel"

[variables]
api_key = { required = true }
pegelonline_api_url = { default = "https://www.pegelonline.wsv.de/webservices/rest-api/v2"}
stations_store_name = { default = "stations" }
measurement_db_name = { default = "measurements" }

log_level = { default = "info" }

[[trigger.http]]
route = "/..."
component = "wasserspiegel"

[component.wasserspiegel]
source = "main.wasm"
allowed_outbound_hosts = []
[component.wasserspiegel.build]
command = "tinygo build -target=wasip1 -gc=leaking -buildmode=c-shared -no-debug -o main.wasm ."
watch = ["**/main.go", "go.mod"]
[component.wasserspiegel.variables]
store_name = ""

[[trigger.http]]
route = "/stations/..."
component = "stations"

[component.stations]
source = "app/station/main.wasm"
key_value_stores = ["stations"]
allowed_outbound_hosts = ["https://www.pegelonline.wsv.de"]
[component.stations.build]
command = "go mod tidy && tinygo build -target=wasip1 -gc=leaking -buildmode=c-shared -no-debug -o main.wasm ."
workdir = "app/station"
watch = ["**/*.go", "go.mod"]
[component.stations.variables]
api_key = "{{ api_key }}"
api_endpoint = "{{ pegelonline_api_url }}"
store_name = "{{ stations_store_name }}"

[[trigger.http]]
route = "/search/..."
component = "search"

[component.search]
source = "app/search/main.wasm"
key_value_stores = ["stations"]
allowed_outbound_hosts = []

[component.search.build]
command = "go mod tidy && tinygo build -target=wasip1 -gc=leaking -buildmode=c-shared -no-debug -o main.wasm ."
workdir = "app/search"
watch = ["**/*.go", "go.mod"]

[component.search.variables]
stations_store_name = "{{ stations_store_name }}"
api_key = "{{ api_key }}"
log_level = "{{ log_level }}"

[[trigger.http]]
route = "/measurements/..."
component = "measurement"

[component.measurement]
source = "app/measurement/main.wasm"
sqlite_databases = ["measurements"]
key_value_stores = []
allowed_outbound_hosts = []

[component.measurement.build]
command = "go mod tidy && tinygo build -target=wasip1 -gc=leaking -buildmode=c-shared -no-debug -o main.wasm ."
workdir = "app/measurement"
watch = ["**/*.go", "go.mod"]

[component.measurement.variables]
measurement_db_name = "{{ measurement_db_name }}"
api_key = "{{ api_key }}"
log_level = "{{ log_level }}"

[[trigger.http]]
route = "/tasks/..."
component = "task"

[component.task]
source = "app/task/main.wasm"
sqlite_databases = ["measurements"]
key_value_stores = ["stations"]
allowed_outbound_hosts = ["https://www.pegelonline.wsv.de"]

[component.task.build]
command = "go mod tidy && tinygo build -target=wasip1 -gc=leaking -buildmode=c-shared -no-debug -o main.wasm ."
workdir = "app/task"
watch = ["**/*.go", "go.mod"]

[component.task.variables]
measurement_db_name = "{{ measurement_db_name }}"
station_store_name = "{{ stations_store_name }}"
api_endpoint = "{{ pegelonline_api_url }}"
api_key = "{{ api_key }}"
log_level = "debug"

