spin_manifest_version = 2

[application]
name = "wasserspiegel"
version = "0.1.0"
authors = ["Timo Sulg <timgluz@gmail.com>"]
description = "TRML plugin for Wasserspiegel"

[variables]
api_key = { required = true }
pegelonline_api_url = { default = "https://www.pegelonline.wsv.de/webservices/rest-api/v2"}
stations_store_name = { default = "stations" }
log_level = { default = "info" }

[[trigger.http]]
route = "/..."
component = "wasserspiegel"



[component.wasserspiegel]
source = "main.wasm"
allowed_outbound_hosts = []
[component.wasserspiegel.build]
command = "tinygo build -target=wasip1 -gc=leaking -buildmode=c-shared -no-debug -o main.wasm ."
watch = ["**/main.go", "go.mod"]
[component.wasserspiegel.variables]
api_endpoint = "{{ pegelonline_api_url }}"
api_key = ""
store_name = ""

[[trigger.http]]
route = "/stations/..."
component = "stations"


[component.stations]
source = "stations.wasm"
key_value_stores = ["stations"]
allowed_outbound_hosts = ["https://www.pegelonline.wsv.de"]
[component.stations.build]
command = "tinygo build -target=wasip1 -gc=leaking -buildmode=c-shared -no-debug -o stations.wasm stations.go"
watch = ["stations.go", "station/**/*.go", "go.mod"]
[component.stations.variables]
api_key = "{{ api_key }}"
api_endpoint = "{{ pegelonline_api_url }}"
store_name = "{{ stations_store_name }}"

[[trigger.http]]
route = "/search/..."
component = "search"

[component.search]
source = "search/main.wasm"
allowed_outbound_hosts = []

[component.search.build]
command = "go mod tidy && tinygo build -target=wasip1 -gc=leaking -buildmode=c-shared -no-debug -o main.wasm ."
workdir = "search"
watch = ["**/*.go", "go.mod"]

[component.search.variables]
stations_store_name = "{{ stations_store_name }}"
api_key = "{{ api_key }}"
log_level = "{{ log_level }}"


